import type { JournalTemplate } from "@/types/templates"

export const journalTemplates: JournalTemplate[] = [
  {
    id: "free-form",
    name: "Free Writing",
    description: "Express your thoughts freely without any structure",
    icon: "Pencil",
    color: "purple",
    prompts: [
      {
        id: "entry",
        question: "How are you feeling today?",
        type: "text",
        placeholder: "Start writing about your day, thoughts, or feelings...",
        required: true,
      },
    ],
  },
  {
    id: "gratitude",
    name: "Gratitude Journal",
    description: "Focus on appreciation and positive aspects of your life",
    icon: "Heart",
    color: "pink",
    prompts: [
      {
        id: "grateful-for",
        question: "What are three things you're grateful for today?",
        type: "text",
        placeholder: "List three things that brought you joy or that you appreciate...",
        required: true,
      },
      {
        id: "why-grateful",
        question: "Why are these things meaningful to you?",
        type: "text",
        placeholder: "Reflect on why these things matter to you...",
        required: false,
      },
      {
        id: "gratitude-rating",
        question: "How grateful do you feel overall today?",
        type: "rating",
        required: true,
      },
    ],
  },
  {
    id: "reflection",
    name: "Daily Reflection",
    description: "Reflect on your experiences and emotions",
    icon: "Sparkles",
    color: "blue",
    prompts: [
      {
        id: "highlights",
        question: "What were the highlights of your day?",
        type: "text",
        placeholder: "The best moments or achievements today...",
        required: true,
      },
      {
        id: "challenges",
        question: "What challenges did you face today?",
        type: "text",
        placeholder: "Difficulties or obstacles you encountered...",
        required: true,
      },
      {
        id: "emotions",
        question: "Which emotions were most present for you today?",
        type: "multiselect",
        options: [
          "Joy",
          "Sadness",
          "Anger",
          "Fear",
          "Surprise",
          "Disgust",
          "Trust",
          "Anticipation",
          "Contentment",
          "Anxiety",
          "Frustration",
          "Hope",
        ],
        required: true,
      },
      {
        id: "lessons",
        question: "What did you learn today?",
        type: "text",
        placeholder: "Insights, lessons, or realizations...",
        required: false,
      },
    ],
  },
  {
    id: "stress-management",
    name: "Stress Management",
    description: "Track and manage your stress levels",
    icon: "Gauge",
    color: "orange",
    prompts: [
      {
        id: "stress-level",
        question: "How would you rate your stress level today?",
        type: "rating",
        required: true,
      },
      {
        id: "stress-sources",
        question: "What were your main sources of stress today?",
        type: "text",
        placeholder: "List the situations, thoughts, or people that caused stress...",
        required: true,
      },
      {
        id: "coping-strategies",
        question: "What strategies did you use to cope with stress?",
        type: "multiselect",
        options: [
          "Deep breathing",
          "Physical exercise",
          "Meditation",
          "Talking to someone",
          "Taking a break",
          "Listening to music",
          "Spending time in nature",
          "Creative expression",
          "Setting boundaries",
          "Problem-solving",
          "None",
        ],
        required: true,
      },
      {
        id: "effectiveness",
        question: "How effective were your coping strategies?",
        type: "rating",
        required: false,
      },
    ],
  },
  {
    id: "goal-setting",
    name: "Goal Setting",
    description: "Set intentions and track your progress",
    icon: "Target",
    color: "green",
    prompts: [
      {
        id: "daily-goals",
        question: "What are your top 3 goals for today or tomorrow?",
        type: "text",
        placeholder: "List your most important goals...",
        required: true,
      },
      {
        id: "goal-progress",
        question: "What progress did you make on your previous goals?",
        type: "text",
        placeholder: "Reflect on steps taken toward your goals...",
        required: true,
      },
      {
        id: "obstacles",
        question: "What obstacles might prevent you from achieving these goals?",
        type: "text",
        placeholder: "Consider potential challenges...",
        required: false,
      },
      {
        id: "motivation-level",
        question: "How motivated do you feel to achieve your goals?",
        type: "rating",
        required: true,
      },
    ],
  },
  {
    id: "self-compassion",
    name: "Self-Compassion",
    description: "Practice kindness and understanding toward yourself",
    icon: "Smile",
    color: "teal",
    prompts: [
      {
        id: "difficult-experience",
        question: "Describe a difficult experience or emotion you're facing",
        type: "text",
        placeholder: "Write about something challenging you're going through...",
        required: true,
      },
      {
        id: "common-humanity",
        question: "How might others also experience similar difficulties?",
        type: "text",
        placeholder: "Reflect on how this is part of the shared human experience...",
        required: true,
      },
      {
        id: "self-kindness",
        question: "What would you say to a friend facing the same situation?",
        type: "text",
        placeholder: "Offer the same kindness to yourself that you would to a friend...",
        required: true,
      },
      {
        id: "self-care",
        question: "What is one way you can take care of yourself today?",
        type: "text",
        placeholder: "Consider a small act of self-care...",
        required: false,
      },
    ],
  },
]

export function getTemplateById(id: string): JournalTemplate | undefined {
  return journalTemplates.find((template) => template.id === id)
}
